### ISSUE TITLE
Alphanumerical Branch Fails Sometimes

### ISSUE THREAD

**Issue by Rayquaza01** [Max1Truc/crypt#1]
@Max1Truc  Hello,
In the pull request to authenticator, you used the alphanumerical branch of this library. Because of Rayquaza01/authenticator#18, I noticed that the alphanumerical branch fails with certain passwords and codes, but not others.

An example of the code that fails:
```javascript
let pass = "8726";
let text = "NGIAFG";
let decrypt = decrypt(crypt(text, pass), pass); // returns NG0AFG, not NGIAFG
console.log(decrypt === text); // false
```

See also: https://jsfiddle.net/gmjo4hzx/

**Comment by Max1Truc** [comment]
@Rayquaza01 Hi,

Sorry, I didn't find out this bug by myself.
It seems to be a mathematical problem.
I'm looking for a fix.

**EDIT:** Found the bug in the decrypt function and confirmed it is some mathematical problem

**Comment by Max1Truc** [comment]
@Rayquaza01 :cry: 
I found the problem, it is here:
```javascript
const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890 "
```
Look at the end:
> yz**0**123456789**0** "

Ok, I just typed two times the "0" number :sob:.
I'll fix it in one minute...

**EDIT:** Fixed
